// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(NewshoreDbContext))]
    [Migration("20210524091708_Reservation")]
    partial class Reservation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Entities.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArrivalStation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartureStation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransportFligthNumber")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TransportFligthNumber");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("Model.Entities.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Number")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Passengers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Mail = "jperez@gmail.com",
                            Name = "Juan Perez",
                            Number = 5493416335598L
                        },
                        new
                        {
                            Id = 2,
                            Mail = "mgarcia@gmail.com",
                            Name = "Manuel Garcia",
                            Number = 5493415887744L
                        },
                        new
                        {
                            Id = 3,
                            Mail = "alberto@gmail.com",
                            Name = "Alberto Perez",
                            Number = 5493415847744L
                        });
                });

            modelBuilder.Entity("Model.Entities.Reservation", b =>
                {
                    b.Property<string>("PNR")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Passenger1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Passenger2Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PNR");

                    b.HasIndex("Passenger1Id");

                    b.HasIndex("Passenger2Id");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Model.Entities.Transport", b =>
                {
                    b.Property<string>("FligthNumber")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FligthNumber");

                    b.ToTable("Transports");
                });

            modelBuilder.Entity("Model.Entities.Flight", b =>
                {
                    b.HasOne("Model.Entities.Transport", "Transport")
                        .WithMany()
                        .HasForeignKey("TransportFligthNumber");

                    b.Navigation("Transport");
                });

            modelBuilder.Entity("Model.Entities.Reservation", b =>
                {
                    b.HasOne("Model.Entities.Passenger", "Passenger1")
                        .WithMany()
                        .HasForeignKey("Passenger1Id");

                    b.HasOne("Model.Entities.Passenger", "Passenger2")
                        .WithMany()
                        .HasForeignKey("Passenger2Id");

                    b.Navigation("Passenger1");

                    b.Navigation("Passenger2");
                });
#pragma warning restore 612, 618
        }
    }
}
